languageCode = "en"
languageName = "English"
weight = 1

title = "n3tuk Documentation"
copyright = "&copy; Jonathan Wright, 2023"

[params]
  isoCode = "en"
  displayName = "en"
  rtl = false
  dateFormat = "2 January 2006"

[author]
  name = "Jonathan Wright"
  # image = "img/author.jpg"
  headline = "n3tuk Owner"
  bio = "The owner and creator of n3tuk"
  links = [
    { email = "mailto:jon@than.io" },
    { github = "https://github.com/jonathanio" },
    { reddit = "https://reddit.com/user/jonathanio" },
    { link = "https://jon.than.io/" },
  ]
