[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Documentation"
  pageRef = "documentation"
  weight = 20

[[main]]
  name = "RFCs"
  pageRef = "rfcs"
  weight = 21

[[main]]
  name = "Runbooks"
  pageRef = "runbooks"
  weight = 22

[[main]]
  name = "Incidents"
  pageRef = "incidents"
  weight = 23

[[main]]
  name = "GitHub"
  url = "https://github.com/n3tuk"
  weight = 98
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Documentation"
  pageRef = "documentation"
  weight = 10

[[footer]]
  name = "RFCs"
  pageRef = "rfcs"
  weight = 12

[[footer]]
  name = "Runbooks"
  pageRef = "runbooks"
  weight = 13

[[footer]]
  name = "Incidents"
  pageRef = "incidents"
  weight = 14

[[footer]]
  name = "Hardware"
  pageRef = "hardware"
  weight = 15

[[footer]]
  name = "Network"
  pageRef = "network"
  weight = 16

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 99
