---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
    # - id: no-commit-to-branch
    #   name: Check this commit is not to the main/master branch
      - id: check-merge-conflict
        name: Check for merge conflicts before committing
      - id: check-case-conflict
        name: Check for case conflicts for case-sensitive filesystems
      - id: check-symlinks
        name: Check for broken syslinks in the repository
      - id: destroyed-symlinks
        name: Check for destroyed symlinks in the repository
      - id: check-added-large-files
        name: Check no large files have been added to the commit
      - id: trailing-whitespace
        name: Check all trailing whitespace is removed
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: Check all files end in a new-line only

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: Lint YAML files for correctness and formatting
        args: [--config-file, .yamllint.yaml]

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.35.0
    hooks:
      - id: markdownlint
        name: Check Markdown correctness and formatting

  - repo: https://github.com/zricethezav/gitleaks.git
    rev: v8.17.0
    hooks:
      - id: gitleaks
        name: Check for hard-coded secrets, keys, and credentials
